services:
  downloader:
    container_name: downloader
    build: yt-dlp
    volumes:
      - ./downloads:/downloads
      - ./download.list:/app/download.list
      - ./history.list:/app/history.list
#      - ./yt-dlp-animevost:/etc/yt-dlp/plugins/animevost:ro
    command: "--batch-file download.list -I -24:"
