services:
  downloader:
    container_name: downloader
    build: yt-dlp
    volumes:
      - /media/media/anime:/downloads
      - ./download.list:/app/download.list
      - ./history.list:/app/history.list
    command: "--batch-file download.list -I -24:"
